### ISSUE TITLE
While creating a library, which is better: To display the error log generated by language or catch the error and display a message manually.

### ISSUE THREAD

**Issue by Prakash2403** [iiitv/aua#15]
Suppose I have created a library and in that I have moved a file from source folder to destination folder using `shutil`. Assume that a file with same name exists in destination directory (`shutil` raises error if a file with same name is already present in destination) . Given above case, shall I catch the error and print a helpful message, or leave it unhandled?

In other words, when should we raise an error and when should we leave them unhandled?

**Comment by aviaryan** [comment]
> In other words, when should we raise an error and when should we leave them unhandled?

I guess you mean "...should we catch an error...".

I will say that if the action that is happening is important to the user or the app, then you should catch the error and show a message (or do something). 
But if the action that threw up isn't that important like say deleting old log files, then you can let it go. But it is always a good practice to display a message when such a thing happens.

**Comment by Prakash2403** [comment]
@aviaryan 

> I guess you mean "...should we catch an error...".

Thanks for the correction, Sir.

> But it is always a good practice to display a message when such a thing happens.

A message is displayed even when we leave the error unhandled (like `traceback` in `python`). Let me clarify the question.

While creating a library, which is better: To display the error log generated by language (like `traceback`) or catch the error and display a message manually.

**Comment by aviaryan** [comment]
> While creating a library, which is better: To display the error log generated by language (like traceback) or catch the error and display a message manually.

Okay, I missed the point that you are creating a "library". In that case, you should never display a message. Instead, you should throw exceptions. I guess you should extend the `Exception` class to create custom exceptions that are meaningful for your library. Then when an error occurs, throw those exceptions.
The client using the library will be responsible for catching those exceptions. 
Needless to say, you will have to document these exceptions nicely so that users don't have a hard time.

**Comment by Prakash2403** [comment]
@aviaryan Thanks Sir.
